### ISSUE TITLE
Border in particle 

### ISSUE THREAD

**Issue by charlyg31** [BentoBoxWorld/Border#34]
hello, it would be nice to be able to replace the borders with a particle form a can as suggested by the /bsb border display .
The Minecraft border is not beautiful ...

**Comment by arphox** [comment]
Hi!
Isn't this implemented now? 🙂
Just make these settings and try it out:
```yml
use-wbapi: false
use-barrier-blocks: true
show-by-default: true
show-max-border: true
show-particles: true
```
